import { ReportContext } from "../../core/types.js";
import { list } from "../../utils/markdown.js";

export function outputReadmeTemplate(context: ReportContext): string {
  const projectName = context.scan.root.split(/[\\/]/).pop() ?? "Project";
  const ai = context.aiProjectAnalysis
    ? `\n## AI Teacher Notes\n\n${context.aiProjectAnalysis}\n`
    : "\n## AI Teacher Notes\n\nThis output was generated from local project metadata. Configure an AI provider to enrich the classroom explanation with model-based reasoning.\n";

  return `# ${projectName} SourceClass

Generated by SourceClass, a terminal-native AI code anatomy classroom.

## What This Folder Contains

This folder is organized like a GitBook. Read it from top to bottom if you are new to this codebase, or jump directly to modification, security, or learning sections.

## Project Snapshot

- Root: \`${context.scan.root}\`
- Generated: \`${context.scan.generatedAt}\`
- Mode: \`${context.plan.mode}\`
- Languages requested: \`${context.plan.languages.join(", ")}\`
- Readable files: \`${context.scan.stats.readableFiles}\`
- Ignored/skipped files: \`${context.scan.stats.ignoredFiles}\`
- Estimated first-pass tokens: \`${context.plan.tokenEstimate}\`

## Detected Stack

### Languages

${list(Object.entries(context.scan.languages).map(([language, count]) => `${language}: ${count} file(s)`))}

### Frameworks

${list(context.scan.frameworks)}

### Package Managers

${list(context.scan.packageManagers)}

## Start Here

1. Read \`02-project-map.md\` to see the whole structure.
2. Read \`13-mind-map-navigation.md\` when you want to jump by folder, file, role, or modification zone.
3. Read \`04-execution-flow.md\` to understand how the project starts and moves.
4. Read \`05-file-roles.md\` to learn what each important file does.
5. Read \`07-modification-guide.md\` before changing code.
6. Read \`14-30-day-code-class.md\` if you want a one-month study plan.

${ai}
## Privacy Reminder

SourceClass is a CLI tool. There is no SourceClass server. If AI enrichment was used, selected source snippets may have been sent to the AI provider configured by the user. Secret-like files are skipped by default, and detected secrets are redacted before prompt construction.
`;
}
