from __future__ import annotations

import shutil
from collections import defaultdict
from pathlib import Path

from sourceclass_engine.models import AnalysisPlan, ProjectMap
from sourceclass_engine.planner.learning_path import learning_steps
from sourceclass_engine.planner.security_planner import security_risks
from sourceclass_engine.utils.json_io import write_json
from sourceclass_engine.writers.markdown_writer import bullet, table
from sourceclass_engine.writers.multilingual_writer import english, japanese, korean


def write_gitbook(project_map: ProjectMap, plan: AnalysisPlan, out_dir: str | Path, raw_project_map: dict) -> None:
    out = Path(out_dir)
    clean_generated_subdirs(out)
    out.mkdir(parents=True, exist_ok=True)
    (out / "languages").mkdir(exist_ok=True)
    (out / "data").mkdir(exist_ok=True)

    files = {
        "README.md": readme(project_map, plan),
        "SUMMARY.md": summary(),
        "01-introduction.md": introduction(project_map, plan),
        "02-project-map.md": project_map_page(project_map),
        "03-folder-anatomy.md": folder_anatomy(project_map),
        "04-execution-flow.md": execution_flow(project_map),
        "05-file-roles.md": file_roles(project_map),
        "06-beginner-explanation.md": beginner_explanation(project_map, plan),
        "07-modification-guide.md": modification_guide(project_map),
        "08-learning-path.md": learning_path(project_map, plan),
        "09-build-and-run.md": build_and_run(project_map),
        "10-open-source-comparison.md": open_source_comparison(project_map),
        "11-security-notes.md": security_notes(project_map),
        "12-business-direction.md": business_direction(project_map),
        "13-mind-map-navigation.md": mind_map_navigation(project_map, plan),
        "14-30-day-code-class.md": thirty_day_code_class(project_map, plan),
        "languages/ko.md": korean(project_map, plan),
        "languages/en.md": english(project_map, plan),
        "languages/ja.md": japanese(project_map, plan),
    }

    for relative, content in files.items():
        target = out / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")

    write_json(out / "data" / "project_map.json", raw_project_map)
    write_json(out / "data" / "analysis_plan.json", plan.to_json())
    write_json(out / "data" / "file_roles.json", file_role_data(project_map))
    write_json(out / "data" / "dependency_hints.json", dependency_data(project_map))
    write_json(out / "data" / "mind_map.json", mind_map_data(project_map))
    write_json(out / "data" / "monthly_curriculum.json", monthly_curriculum_data(project_map, plan))


def clean_generated_subdirs(out: Path) -> None:
    for dirname in ["languages", "data"]:
        target = out / dirname
        if target.exists():
            shutil.rmtree(target)


def summary() -> str:
    return """# Summary

- [Introduction](README.md)
- [Project Map](02-project-map.md)
- [Folder Anatomy](03-folder-anatomy.md)
- [Execution Flow](04-execution-flow.md)
- [File Roles](05-file-roles.md)
- [Beginner Explanation](06-beginner-explanation.md)
- [Modification Guide](07-modification-guide.md)
- [Learning Path](08-learning-path.md)
- [Build and Run](09-build-and-run.md)
- [Open Source Comparison](10-open-source-comparison.md)
- [Security Notes](11-security-notes.md)
- [Business Direction](12-business-direction.md)
- [Mind Map Navigation](13-mind-map-navigation.md)
- [30-Day Code Class](14-30-day-code-class.md)
- [Korean](languages/ko.md)
- [English](languages/en.md)
- [Japanese](languages/ja.md)
"""


def readme(project_map: ProjectMap, plan: AnalysisPlan) -> str:
    ai = f"\n## AI Analysis\n\n{plan.ai_summary}\n" if plan.ai_summary else ""
    return f"""# SourceClass Engine Output

Generated by the SourceClass Python analysis engine from a Rust project map.

## What Was Analyzed

- Project root: `{project_map.project_root}`
- Rust map generated at: `{project_map.generated_at}`
- Files included: `{project_map.stats.get("includedFiles", 0)}`
- Files ignored: `{project_map.stats.get("ignoredFiles", 0)}`
- Mode: `{plan.mode}`
- Languages requested: `{", ".join(plan.languages)}`

## Detected Stack

- Languages: `{", ".join(project_map.detected_stack.get("languages", [])) or "Unknown"}`
- Frameworks: `{", ".join(project_map.detected_stack.get("frameworks", [])) or "None detected"}`
- Package managers: `{", ".join(project_map.detected_stack.get("packageManagers", [])) or "None detected"}`
- Build tools: `{", ".join(project_map.detected_stack.get("buildTools", [])) or "None detected"}`

## Main Entry Points

{bullet([f"`{item}`" for item in project_map.detected_stack.get("entryPoints", [])])}

## Most Important Files

{bullet([f"`{item}`" for item in plan.important_files[:16]])}

## Suggested Reading Order

{numbered(plan.learning_files[:10])}

## v3 Learning UX

- [Mind Map Navigation](13-mind-map-navigation.md): jump from folder to file to role to modification zone.
- [30-Day Code Class](14-30-day-code-class.md): follow a one-month project learning curriculum.

## Warnings

{bullet(project_map.warnings + plan.skipped_notes)}
{ai}
## Privacy Reminder

SourceClass is CLI-first. There is no SourceClass server. If AI mode was used, selected project-map content may have been sent directly to the configured provider. API keys are read from environment variables and are never written to generated docs.
"""


def introduction(project_map: ProjectMap, plan: AnalysisPlan) -> str:
    return f"""# Introduction

This documentation explains the structure, role, execution flow, modification points, learning path, and security posture of the scanned project.

## Project Identity

The Rust scanner detected `{len(project_map.files)}` included files across `{len(project_map.folders)}` folders.

## Engine Pipeline

1. Rust scanned the project and generated `project_map.json`.
2. Python loaded the map, planned analysis, and wrote GitBook-style Markdown.
3. Optional AI provider enrichment can add deeper teaching notes.

## Mode

`{plan.mode}`
"""


def project_map_page(project_map: ProjectMap) -> str:
    rows = [
        [folder.path, str(folder.file_count), ", ".join(folder.role_hints)]
        for folder in project_map.folders
    ]
    return f"""# Project Map

{table(["Folder", "Files", "Role Hints"], rows)}

## Language Breakdown

{bullet([f"{language}: {count}" for language, count in project_map.stats.get("languageBreakdown", {}).items()])}
"""


def folder_anatomy(project_map: ProjectMap) -> str:
    return f"""# Folder Anatomy

{table(["Folder", "File Count", "Role Hints"], [[folder.path, str(folder.file_count), ", ".join(folder.role_hints)] for folder in project_map.folders])}
"""


def execution_flow(project_map: ProjectMap) -> str:
    rows = [
        [file.path, ", ".join(file.dependency_hints[:12])]
        for file in project_map.files
        if file.dependency_hints
    ][:120]
    return f"""# Execution Flow

## Entry Points

{bullet([f"`{item}`" for item in project_map.detected_stack.get("entryPoints", [])])}

## Dependency Hints

{table(["File", "Dependency Hints"], rows) if rows else "No dependency hints were detected."}
"""


def file_roles(project_map: ProjectMap) -> str:
    rows = [
        [file.path, file.language, ", ".join(file.role_hints), str(len(file.chunk_plan)), "yes" if file.cache_hit else "no"]
        for file in project_map.files
    ]
    return f"""# File Roles

{table(["File", "Language", "Role Hints", "Chunks", "Cache Hit"], rows)}
"""


def beginner_explanation(project_map: ProjectMap, plan: AnalysisPlan) -> str:
    return f"""# Beginner Explanation

Think of this project as a classroom map:

- Entry points show where the program starts.
- Dependency manifests show what tools and libraries are needed.
- Services, routes, models, and utilities show how responsibilities are divided.
- Tests show expected behavior.
- Security-sensitive files should be edited only after careful reading.

## First Reading Mission

{numbered(plan.learning_files[:8])}
"""


def modification_guide(project_map: ProjectMap) -> str:
    safe = [file.path for file in project_map.files if any(role in file.role_hints for role in ["documentation", "test", "utility", "component"])]
    dangerous = [file.path for file in project_map.files if any(role in file.role_hints for role in ["security_sensitive", "environment", "database", "build_script", "dependency_manifest"])]
    return f"""# Modification Guide

## Project Diagnosis

- Included files: `{project_map.stats.get("includedFiles", 0)}`
- Ignored paths: `{project_map.stats.get("ignoredFiles", 0)}`
- Entry points: `{", ".join(project_map.detected_stack.get("entryPoints", [])) or "None detected"}`
- Main languages: `{", ".join(project_map.detected_stack.get("languages", [])) or "Unknown"}`

## Safe Edit Zones

{bullet([f"`{item}`" for item in safe[:40]])}

## Dangerous Edit Zones

{bullet([f"`{item}`" for item in dangerous[:40]])}

## 30-Day Improvement Plan

1. Week 1: Read entry points, manifests, and docs.
2. Week 2: Add or run tests around one small behavior.
3. Week 3: Improve one safe file and document the change.
4. Week 4: Review security-sensitive and build files before any larger refactor.
"""


def learning_path(project_map: ProjectMap, plan: AnalysisPlan) -> str:
    algorithm = natural_language_algorithm(project_map)
    education = ""
    if plan.mode == "education":
        education = f"""
## Course-Style Lessons

1. Map the project entry point.
2. Follow dependency hints from entry point to service/model code.
3. Explain one function or module in plain language.
4. Identify one safe change and one dangerous change.
5. Write a short reflection about what the architecture is trying to protect.

## Natural-Language Algorithm

{algorithm}
"""
    return f"""# Learning Path

For the SourceClass v3 one-month curriculum, continue to [30-Day Code Class](14-30-day-code-class.md).

## Reading Order

{numbered(plan.learning_files)}
{education}

## Practice Missions

{bullet(learning_steps(plan))}

## Mini Quiz

1. Which file starts the project?
2. Which file declares dependencies?
3. Which folders are safe for first changes?
4. Which files are security-sensitive?
5. What command would you run after a small change?
"""


def natural_language_algorithm(project_map: ProjectMap) -> str:
    entry_points = project_map.detected_stack.get("entryPoints", [])
    first = entry_points[0] if entry_points else "the main entry file"
    return "\n".join(
        [
            f"1. Start at `{first}`.",
            "2. Read imports or dependency hints to find the next files.",
            "3. Separate setup/config code from business logic.",
            "4. Follow service, model, database, or route files depending on the project type.",
            "5. Confirm behavior through tests or documentation before editing.",
        ]
    )


def build_and_run(project_map: ProjectMap) -> str:
    manifests = [file.path for file in project_map.files if "dependency_manifest" in file.role_hints]
    return f"""# Build and Run

SourceClass does not execute project code or install dependencies.

## Dependency Manifests

{bullet([f"`{item}`" for item in manifests])}

## Suggested Next Step

Read the project README and dependency manifest before running installation or build commands.
"""


def open_source_comparison(project_map: ProjectMap) -> str:
    keywords = " ".join(project_map.detected_stack.get("languages", [])[:4]) or "code analysis"
    return f"""# Open Source Comparison

SourceClass does not scrape repositories aggressively.

## Safe Search Queries

- `topic:cli topic:documentation {keywords} license:mit`
- `topic:code-analysis topic:ai documentation cli`
- `"{keywords}" "MIT" "GitHub"`

## Compare

- License
- CLI design
- Architecture
- Test coverage
- Security posture
- Documentation quality
"""


def security_notes(project_map: ProjectMap) -> str:
    risks = security_risks(project_map)
    return f"""# Security Notes

> This is best-effort security guidance and not a replacement for a professional security audit.

## Security Risk Table

{table(["File", "Risk", "Mitigation"], [[risk["file"], risk["risk"], risk["mitigation"]] for risk in risks]) if risks else "No security-sensitive files were detected by role hints."}

## Checklist

- Do not print or commit API keys.
- Do not analyze private code with an AI provider you do not trust.
- Use local models for sensitive code.
- Review input/output boundaries.
- Review build and deployment scripts.
- Review dependency manifests and lockfiles.
"""


def business_direction(project_map: ProjectMap) -> str:
    stack = ", ".join(project_map.detected_stack.get("languages", [])) or "software"
    return f"""# Business Direction

This project appears to be a `{stack}` codebase.

## Practical Direction

- Identify the smallest useful user-facing behavior.
- Keep the core open-source if this becomes a public tool.
- Use sponsorships, consulting, workshops, or custom deployment before paywalling core learning features.
- Improve onboarding docs and tests before expanding scope.
"""


def mind_map_navigation(project_map: ProjectMap, plan: AnalysisPlan) -> str:
    folder_rows = []
    files_by_folder: dict[str, list] = defaultdict(list)
    for file in project_map.files:
        folder = str(Path(file.path).parent).replace("\\", "/")
        folder = "/" if folder == "." else folder
        files_by_folder[folder].append(file)

    for folder, files in sorted(files_by_folder.items()):
        roles = sorted({role for file in files for role in file.role_hints})
        representative = ", ".join(f"`{file.path}` ({', '.join(file.role_hints[:2])})" for file in files[:6])
        folder_rows.append([folder, str(len(files)), ", ".join(roles), representative, best_next_page(files)])

    return f"""# Mind Map Navigation

SourceClass v3 turns the generated docs into an explorable code map. Use this page when you want to move from folder to file to role to modification point without reading every page in order.

## Navigation Buttons

[Project Map](02-project-map.md) | [Execution Flow](04-execution-flow.md) | [File Roles](05-file-roles.md) | [Modification Guide](07-modification-guide.md) | [30-Day Class](14-30-day-code-class.md)

## Explorer Routes

### Start Route

1. Open [Project Map](02-project-map.md).
2. Jump to the entry point below.
3. Follow dependency hints in [Execution Flow](04-execution-flow.md).
4. Return here when the structure gets confusing.

### Modify Route

1. Choose a folder or file from the map.
2. Check role hints and risk level.
3. Read [Modification Guide](07-modification-guide.md).
4. Make one small change and verify it.

### Learning Route

1. Read today's mission in [30-Day Code Class](14-30-day-code-class.md).
2. Open the linked focus file from this map.
3. Write purpose, input, output, and connection.
4. Move to the next day after you can explain the current file.

## Entry Point Jump

{bullet([f"`{item}` -> [Execution Flow](04-execution-flow.md)" for item in project_map.detected_stack.get("entryPoints", [])])}

## Folder To File Map

{table(["Folder", "Files", "Role Hints", "Representative Files", "Best Next Page"], folder_rows)}

## Learning Files

{bullet([f"`{item}`" for item in plan.learning_files[:20]])}
"""


def thirty_day_code_class(project_map: ProjectMap, plan: AnalysisPlan) -> str:
    lessons = monthly_curriculum_data(project_map, plan)
    return f"""# 30-Day Code Class

SourceClass v3 turns one project into a one-month code class. The goal is to understand structure, flow, role, modification points, and learning direction one day at a time.

## How To Study

- Spend 20 to 60 minutes per day.
- Keep four notes for each file: role, input, output, connection.
- Do not edit risky files until the mission says so.
- Day 30 ends with one safe direct modification mission.

## 30-Day Curriculum

{table(["Day", "Theme", "Focus", "Mission", "Daily Output"], [[f"Day {item['day']}", item["theme"], item["focus"], item["mission"], item["output"]] for item in lessons])}

## Final Goal

By Day 30, you should be able to explain what this project is, where it starts, how it flows, what can be modified safely, what should be handled carefully, and what you would build next.
"""


def file_role_data(project_map: ProjectMap) -> list[dict]:
    return [{"path": file.path, "language": file.language, "roleHints": file.role_hints} for file in project_map.files]


def dependency_data(project_map: ProjectMap) -> list[dict]:
    return [{"path": file.path, "dependencyHints": file.dependency_hints} for file in project_map.files if file.dependency_hints]


def mind_map_data(project_map: ProjectMap) -> dict:
    folders: dict[str, list[dict]] = defaultdict(list)
    for file in project_map.files:
        folder = str(Path(file.path).parent).replace("\\", "/")
        folder = "/" if folder == "." else folder
        folders[folder].append(
            {
                "path": file.path,
                "language": file.language,
                "roleHints": file.role_hints,
                "dependencyHints": file.dependency_hints,
                "chunkCount": len(file.chunk_plan),
            }
        )
    return {
        "schemaVersion": "sourceclass.mindMap.v1",
        "folders": folders,
        "entryPoints": project_map.detected_stack.get("entryPoints", []),
    }


def monthly_curriculum_data(project_map: ProjectMap, plan: AnalysisPlan) -> list[dict]:
    entry = first(project_map.detected_stack.get("entryPoints", []), first(plan.learning_files, "README/config files"))
    manifests = [file.path for file in project_map.files if "dependency_manifest" in file.role_hints]
    tests = [file.path for file in project_map.files if "test" in file.role_hints]
    safe = first([file.path for file in project_map.files if any(role in file.role_hints for role in ["documentation", "test", "utility", "component"])], "a safe documentation or utility file")
    risky = first([file.path for file in project_map.files if any(role in file.role_hints for role in ["security_sensitive", "environment", "database", "build_script", "dependency_manifest"])], "a config, entry, database, or security-sensitive file")
    learning = plan.learning_files

    def pick(index: int, fallback: str) -> str:
        return learning[index] if index < len(learning) else fallback

    return [
        day(1, "Project Orientation", "Whole structure", "Read README, SUMMARY, and Project Map.", "One-paragraph project summary"),
        day(2, "Entry Point", entry, "Open the entry point and write what happens first.", "Startup flow notes"),
        day(3, "Folder Map", "Folders", "Explain each top-level folder in one sentence.", "Folder role list"),
        day(4, "Config and Packages", ", ".join(manifests[:3]) or "dependency manifests", "Find package manager, scripts, and key config files.", "Build/config checklist"),
        day(5, "Execution Flow", pick(0, entry), "Follow imports or dependency hints from the entry point.", "Flow diagram in text"),
        day(6, "Core File 1", pick(1, entry), "Explain purpose, input, output, and dependencies.", "File anatomy note"),
        day(7, "Core File 2", pick(2, entry), "Find how this file connects to the rest of the project.", "Connection map"),
        day(8, "API or Interface", pick(3, "API/interface files"), "Identify how external input enters the system.", "Input boundary notes"),
        day(9, "Service Logic", pick(4, "service or utility files"), "Separate setup code from business logic.", "Logic summary"),
        day(10, "Data Shape", pick(5, "model/schema/database files"), "Find models, schemas, or data contracts.", "Data concept list"),
        day(11, "Utility Layer", pick(6, "utility/helper files"), "Find reusable helpers and who uses them.", "Utility dependency note"),
        day(12, "Tests", ", ".join(tests[:3]) or "test files", "Read one test and explain the protected behavior.", "Test explanation"),
        day(13, "Error Paths", pick(7, "error-handling files"), "Search for error, validation, fallback, or exception logic.", "Likely error list"),
        day(14, "Environment", ".env.example and config", "Find environment variables without opening secret files.", "Environment variable map"),
        day(15, "Security Basics", risky, "Read security-sensitive notes before modifying risky files.", "Risk checklist"),
        day(16, "Build and Run", "Build scripts", "Read scripts and build instructions without executing unknown code.", "Run/build command notes"),
        day(17, "Dependency Review", "Manifests and imports", "List important external dependencies.", "Dependency purpose list"),
        day(18, "Modification Zones", safe, "Classify safe, caution, and dangerous edit zones.", "Modification compass"),
        day(19, "Tiny Safe Change Plan", safe, "Plan a harmless edit but do not make it yet.", "Change plan"),
        day(20, "Refactor Reading", pick(8, "shared code"), "Find naming or duplication issues without editing.", "Refactor candidates"),
        day(21, "Open Source Comparison", "Similar projects", "Use generated search queries to compare architecture.", "Comparison notes"),
        day(22, "Business Direction", "Usefulness", "Explain who would use this project and why.", "User pain point note"),
        day(23, "Documentation Improvement", "Docs", "Find one missing setup or explanation detail.", "Documentation patch idea"),
        day(24, "Test Improvement", ", ".join(tests[:3]) or "test files", "Design one new test for safe behavior.", "Test case outline"),
        day(25, "Security Review", risky, "Review keys, input, permissions, dependencies, and filesystem risks.", "Security table update"),
        day(26, "Packaging Review", ", ".join(manifests[:3]) or "build config", "Find how this project could be packaged or released.", "Packaging checklist"),
        day(27, "Learning Teachback", pick(9, entry), "Teach one file as if explaining to a beginner.", "Beginner lesson note"),
        day(28, "Mini Architecture Doc", "Whole project", "Write architecture in five bullets.", "Five-bullet architecture"),
        day(29, "Change Rehearsal", safe, "Prepare exact files and verification steps for a small change.", "Final change checklist"),
        day(30, "Direct Modification Mission", safe, "Make one safe change, verify it, and document what changed.", "Completed modification report"),
    ]


def best_next_page(files: list) -> str:
    roles = {role for file in files for role in file.role_hints}
    if "entry_point" in roles or "possible_entry_point" in roles:
        return "[Execution Flow](04-execution-flow.md)"
    if "security_sensitive" in roles or "environment" in roles:
        return "[Security Notes](11-security-notes.md)"
    if "dependency_manifest" in roles or "build_script" in roles:
        return "[Build and Run](09-build-and-run.md)"
    if "test" in roles:
        return "[Learning Path](08-learning-path.md)"
    return "[File Roles](05-file-roles.md)"


def day(day_number: int, theme: str, focus: str, mission: str, output: str) -> dict:
    return {"day": day_number, "theme": theme, "focus": focus, "mission": mission, "output": output}


def first(items, fallback: str) -> str:
    return items[0] if items else fallback


def numbered(items: list[str]) -> str:
    if not items:
        return "1. No confident reading order was detected."
    return "\n".join(f"{index}. `{item}`" for index, item in enumerate(items, start=1))
